# Generated by Django 2.2.16 on 2023-05-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230527_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='shop',
            new_name='shops',
        ),
    ]
